const products = [
  {
    _id: '1',
    name: 'Airpods Wireless',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '2',
    name: 'Iphone 11 pro ',
    image: '/images/phone.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'Iphone',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 3.5,
    numReviews: 4,
  },
  {
    _id: '3',
    name: 'Cannon Camera',
    image: '/images/camera.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '4',
    name: 'Playstation 5',
    image: '/images/playstation.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'sony',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '5',
    name: 'Logitech Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'Logitech',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '6',
    name: 'Amazon Eco Dot',
    image: '/images/alexa.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly high qulaity aac audio offers immersive listening experience built-in microphone allows you to take calls while working',
    brand: 'Amazon',
    category: 'Electornics',
    price: 89.0,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
]
export default products;